### ISSUE TITLE
Invalid version string in login

### ISSUE THREAD

**Issue by hessu** [Guru-RF/LoraAPRSGateway#2]
https://github.com/Guru-RF/LoraAPRSGateway/blob/d9ff2651c9a74591801b72f998b2bb71b3c973bc/code.py#L100

The APRS-IS client version string should be two words, which are not quoted. One word for the name of the software, another word for the version number:

   **vers loragw 1.2.3-456**

**Comment by ure** [comment]
thx, fixed !
